#!/bin/sh
# BOOT-Skript fürs initramfs (BOOT=boot-9p): mountet das Root-Dateisystem per 9p aus dem Emulator. Die übrigen
# Schritte (mount_top, mount_premount, ...) kommen aus /scripts/local, das init vorher lädt.
mountroot() {
	mount -n -t 9p -o trans=virtio,version=9p2000.L,cache=loose,rw host9p "${rootmnt}"
}
